title: Comite Savoie
email: praginel@free.fr
description: >-
  Site du comité de Savoie : Natation, Water-polo et Eau Libre
baseurl: "/comitesavoienwp"
url: "https://praginel.github.io/"
github_username:  praginel

# Build settings
theme: minima
lang: fr
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
last-modified-at:
    date-format: '%Y-%m-%d %H:%M'
exclude:
  # - VieuxSite/
  # - pdfs/
  # - images/
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
